name: Build and Push CartService (.NET)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # ajustá según la versión que uses

    - name: Restore dependencies
      run: dotnet restore cartservice.sln

    - name: Build
      run: dotnet build cartservice.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test tests/cartservice.tests.csproj --configuration Release --verbosity normal


    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t martin555/cartservice:latest ./src
        docker push martin555/cartservice:latest

